name: Notification

on:
  push:
    branches:
      - main

jobs:
  push_notification:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: success
        uses: Ilshidur/disco rd-webhook-notify@v1
        if: success()
        continue-on-error: true
        with:
          severity: info
          details: Push to main branch succeeded!
          webhookURL: ${{ secrets.DISCORD_WEBOHOOK }}
      - name: failure
        uses: Ilshidur/disco rd-webhook-notify@v1
        if: failure()
        continue-on-error: true
        with:
          severity: error
          details: Push to main branch failed!
          webhookURL: ${{ secrets.DISCORD_WEBOHOOK }}
      - name: cancelled
        uses: Ilshidur/disco rd-webhook-notify@v1
        if: cancelled()
        continue-on-error: true
        with:
          severity: warn
          details: Push to main branch was cancelled!
          webhookURL: ${{ secrets.DISCORD_WEBOHOOK }}
