name: Notification

on:
  push:
    branches:
      - main

jobs:
  push_notification:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: success
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ success() }}
        with:
          severity: info
          details: Test Succeeded!
          webhookUrl: ${{secrets.DISCORD_WEBHOOK}}
      - name: failure
        uses: rjstone/discord-webhook-notify@v1
        if: ${{failure()}}
        with:
          severity: error
          details: Test Failed!
          webhookUrl: ${{secrets.DISCORD_WEBHOOK}}
      - name: cancelled
        uses: rjstone/discord-webhook-notify@v1
        if: ${{cancelled}}
        with:
          severity: warn
          details: Test Cancelled!
          webhookUrl: ${{secrets.DISCORD_WEBHOOK}}
